### ISSUE TITLE
Exception thrown when no tables exist, improve error message

### ISSUE THREAD

**Issue by dennisroche** [jbogard/Respawn#46] opened 2018-04-28 16:19 UTC
As expected, `Respawn` cannot do anything without tables for reset. 

However, it should fail gracefully and with a useful error message that is the case. Currently it throws
`BeginExecuteNonQuery: CommandText property has not been initialized`.

It is an unlikely scenario and I only found this due to an EF Core not finding the migrations assembly from the context of the project context.

I'll put together a PR soon for this.

**Comment by lesair** [comment] 2019-09-06 13:11
@dennisroche , I stumbled upon this as exception as well while trying to `Checkpoint.Reset` an SQL database in Azure I forgot to create its tables. My first thought was "please don't tell me Respawn has issues with SQL databases in Azure", but then I discarded that thought because it really made no sense, and started digging into the aforementioned exception, until I reached this issue and I realized I forgot to initialize my database.

I believe a more meaningful error message or exception would have led me to the root cause faster.

**Comment by Inspyro** [comment] 2020-08-20 07:58
As a workaround you can decorate the DbAdapter like so:
```
new Checkpoint
{
  SchemasToInclude = ..., TablesToIgnore = ...
  DbAdapter = new EmptyCommandHandlingDbAdapterDecorator(DbAdapter.SqlServer)
}
```

and override the BuildDeleteCommandText method:
```
public string BuildDeleteCommandText (GraphBuilder builder)
{
  var command = _dbAdapter.BuildDeleteCommandText(builder);

  if (string.IsNullOrEmpty(command))
    throw new NothingToClearException();

  return command;
}
```

but I would also appreciate that this bug was being fixed by throwing a better exception out of the box

**Comment by majouleblanc** [comment] 2022-06-15 11:58
this issue still happening on v5.0.1, i managed to work around it by just replacing 
await Fixture.Checkpoint.Reset(Database.ConnectionStringAdmin); 
by 
VotingContext.Votes.RemoveRange(VotingContext.Votes);
await VotingContext..SaveChangesAsync();

VotingContext.ChangeTracker.Entries()
            .Where(e => e.Entity != null).ToList()
            .ForEach(e => e.State = EntityState.Detached);

**Closed** 2022-09-30 12:11 UTC
